name: CI V2 Docker Compose
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  test-compose-action:
    runs-on: ubuntu-latest
    name: test compose action
    steps:
        - uses: actions/checkout@v3
        - uses: isbang/compose-action@v1.5.1
          with:
            compose-file: "docker-compose.yml"
        - name: Install Cypress
          uses: cypress-io/github-action@v4
          with:
            working-directory: ./hippotech-react
            runTests: false

        - name: Cypress run
          uses: cypress-io/github-action@v4
          with:
            working-directory: ./hippotech-react
            install: false
