name: CI V2 Docker Compose
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  test-compose-action:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      id-token: write
      issues: write
      discussions: write
      packages: write
      repository-projects: write
      security-events: write
      statuses: write
      
    name: Deploy & Test
    
    steps:
      - name: Deploy Docker Containers
      - uses: actions/checkout@v3
      
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "docker-compose.yml"
