on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  test-compose-action:
    runs-on: ubuntu-latest
    name: test compose action
    steps:
        - uses: actions/checkout@v3
        - uses: isbang/compose-action@v1.5.1
          with:
            compose-file: "./docker/docker-compose.yml"
          env:
            CUSTOM_VARIABLE: "test"
